### ISSUE TITLE
bash: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by prof3c1** [MrKaKisen/pterodactyl-installer#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS (please complete the following information):**
 - OS: [e.g. Ubuntu, Debian, CentOS]
 - Installation: [panel or daemon]

**Additional context**

**Comment by MrKaKisen** [comment]
Hi! Thank you for your report.

I've investigated in the cause of this issue and it seems like it has to do with the provided one-liner command in the README. I am unable to solve it right now, but I will hopefully be able to soon.

In the meantime, I would recommend logging in as root and then execute the provided script (so perform `sudo su` and then execute the curl command instead of putting `sudo` in front of the initial command).

**Comment by prof3c1** [comment]
* Python is required in order for this script to work.
* install using apt on Debian/Ubuntu or yum on CentOS
But i  have installed .. Hm iam confused

ut 16. 10. 2018 o 22:02 Vilhelm Prytz <notifications@github.com> napísal(a):

**Comment by MrKaKisen** [comment]
What OS are you running?

**Comment by prof3c1** [comment]
Ubuntu 18.04 i can give you root acess if have enought time sir

Dňa ut 16. 10. 2018 o 22:59 Vilhelm Prytz <notifications@github.com>
napísala(a):

**Comment by MrKaKisen** [comment]
Try installing Python. `sudo apt install python -y`

Then try running the script again. Let me know if this works out.

**Comment by MrKaKisen** [comment]
I think this can be considered resolved. Re-open the issue if you still have issues.
